spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "root"
    password: "OneTool"
    url: "jdbc:mysql://172.17.1.253:3306/Onetool"
  mvc:
    path match:
      matching-strategy: ant-path-matcher

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
knife4j:
  enable: true
  openapi:
    title: 用户管理接口文档
    description: "用户管理接口文档"
    email: 359230294@qq.com
    concat: dlr
    version: v1.0.0
    group:
      default:
        group-name: oneTool Group
        api-rule: package
        api-rule-resources:
          - com.ot.onetool.Controller

